default-scheme = "base16-gruvbox-dark-hard"
shell = "/bin/sh -c '{}'"

[[items]]
name = "tinted-alacritty"
path = "https://github.com/tinted-theming/tinted-alacritty"
themes-dir = "colors"
hook = "$HOME/.local/bin/theme-apply-global %f"

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "sh %f"

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "sh"
