{{- $version := "2.3.0" -}}
[".local/bin/lmk"]
  type = "archive-file"
  url = "https://github.com/fgrehm/lmk/releases/download/v{{ $version }}/lmk_{{ $version }}_Linux_x86_64.tar.gz"
  executable = true
  path = "lmk"
  checksum.sha256 = "d2630ae0426bd8d72ecbba50256b70761462bc20637a9e07f490f35bcfe73ff4"
# vim: ft=toml.gotmpl
