{{- $arch := .chezmoi.arch -}}
{{- if eq $arch "amd64" -}}{{- $arch = "x86_64" -}}{{- else if eq $arch "arm64" -}}{{- $arch = "aarch64" -}}{{- end -}}
{{- $version := "0.19.1" -}}
[".local/bin/delta"]
  type = "archive-file"
  url = "https://github.com/dandavison/delta/releases/download/{{ $version }}/delta-{{ $version }}-{{ $arch }}-unknown-linux-gnu.tar.gz"
  path = "delta-{{ $version }}-{{ $arch }}-unknown-linux-gnu/delta"
  executable = true
