{{- $version := "2.91.0" -}}
[".local/bin/gh"]
  type = "archive-file"
  url = "https://github.com/cli/cli/releases/download/v{{ $version }}/gh_{{ $version }}_linux_amd64.tar.gz"
  path = "gh_{{ $version }}_linux_amd64/bin/gh"
  executable = true
  checksum.sha256 = "304a0d2460f4a8847d2f192bad4e2a32cd9420d28716e7ae32198181b65b5f9c"
# vim: ft=toml.gotmpl
