{{- $version := "0.61.1" -}}
[".local/bin/lazygit"]
  type = "archive-file"
  url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ $version }}/lazygit_{{ $version }}_Linux_x86_64.tar.gz"
  executable = true
  path = "lazygit"
  checksum.sha256 = "1b91e660700f2332696726b635202576b543e2bc49b639830dccd26bc5160d5d"
# vim: ft=toml.gotmpl
