{{- $arch := .chezmoi.arch -}}
{{- if eq $arch "amd64" -}}{{- $arch = "x86_64" -}}{{- else if eq $arch "arm64" -}}{{- $arch = "aarch64" -}}{{- end -}}
[".local/bin/wt"]
  type = "archive-file"
  url = "https://github.com/max-sixty/worktrunk/releases/latest/download/worktrunk-{{ $arch }}-unknown-linux-musl.tar.xz"
  path = "worktrunk-{{ $arch }}-unknown-linux-musl/wt"
  executable = true
# vim: ft=toml.gotmpl
