{{- $version := "0.10.0" -}}
[".local/bin/crib"]
  type = "archive-file"
  url = "https://github.com/fgrehm/crib/releases/download/v{{ $version }}/crib_linux_amd64.tar.gz"
  executable = true
  path = "crib"
  checksum.sha256 = "9a6655fd7f0158ffb088575f24e6652a56d33126d17d09b4fd44e9c4ff4200ec"
# vim: ft=toml.gotmpl
