return {
  -- TODO: Conditionally enable this based on env var (for when I want to use in dev containers)
  -- {
  --   "mason-org/mason-lspconfig.nvim",
  --   opts = {
  --     automatic_enable = {
  --       exclude = { "ruby_lsp" },
  --     },
  --   },
  -- },
  --
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       ruby_lsp = {
  --         mason = false,
  --         cmd = { "bundle", "exec", "ruby-lsp" },
  --       },
  --     },
  --   },
  -- },
}
