# renovate: datasource=github-releases depName=fgrehm/clotilde
{{- $version := "0.10.0" -}}
[".local/bin/clotilde"]
  type = "archive-file"
  url = "https://github.com/fgrehm/clotilde/releases/download/v{{ $version }}/clotilde_linux_{{ .chezmoi.arch }}.tar.gz"
  path = "clotilde"
  executable = true
