{{- $version := "0.12.0" -}}
[".local/bin/clotilde"]
  type = "archive-file"
  url = "https://github.com/fgrehm/clotilde/releases/download/v{{ $version }}/clotilde_linux_amd64.tar.gz"
  path = "clotilde"
  executable = true
  checksum.sha256 = "82ef37d51a7f46db5554ca4714a245b6ce47de57d0cd0b559166e9dfb73d6bb8"
# vim: ft=toml.gotmpl
